### ISSUE TITLE
BinaryAttachment depreciated

### ISSUE THREAD

**Issue by rickfischer** [revetkn/restfb#181]
The "with" method of BiinaryAttachment has been depreciated.  The second parameter no longer accepts an InputStream. The new method requires byte[]
```java
InputStream is = new FileInputStream(photo);
BinaryAttachment ba = BinaryAttachment.with(myFileName, is);  // This is depreciated
```

I attempted to create BinaryAttachment as follows. I found this example on stack overflow, but no luck

```java
File imgPath = new File(ImageName);
BufferedImage bufferedImage = ImageIO.read(imgPath);
// get DataBufferBytes from Raster
WritableRaster raster = bufferedImage .getRaster();
DataBufferByte data   = (DataBufferByte) raster.getDataBuffer();
BinaryAttachment ba = BinaryAttachment.with(myFileName, data.getData());

publishPhotoResponse = facebookClient.publish(alb.getId() + "/photos",FacebookType.class, ba,Parameter.with("message", fbtext),Parameter.with("link", mylink));
```

Returned: FacebookApiException: Invalid parameter (code 100, subcode 1366046)

The publish works find with the old BinaryAttachment

Thanks

**Comment by nbartels** [comment]
I wrote some tiny unit test to reproduce your problem, but I use a different approach to get the byte-array from the file. 

I can reproduce your problem under some special conditions, so here is a list what I tested. The checkd items are working, the others not: 
- [x] Publish to ```<pageid>/photos``` without other parameters
- [ ] Publish to ```<pageid>/feed``` without other parameters
- [x] Publish to ```<pageid>/feed``` with ```message``` parameter 
- [x] Publish to ```<pageid>/feed``` with ```message``` and ```link``` parameter
- [x] Publish to ```<albumid>/photos``` without other parameters
- [x] Publish to ```<albumid>/photos``` with ```message``` parameter 
- [x] Publish to ```<albumid>/photos``` with ```message``` and ```link``` parameter

The last point is working but does not make sense, because the given image is ignored by Facebook, instead the link is used and some image from the website is fetched ...

So I cannot reproduce the issue, nevertheless I add an integration test.
